package net.skds.lib2.misc.clazz.classbuilder;

import net.skds.lib2.annotations.AutoGenerated;
import net.skds.lib2.utils.linkiges.Pair;

import java.lang.reflect.Modifier;
import java.util.*;

public class TextClassBuilder {

	public final String pack;
	public final String name;
	public final ClassType type;

	private int modifiers = Modifier.PUBLIC;

	private CBJavadoc javadoc;

	private final Set<CBAnnotation> annotations = new HashSet<>();
	private final Set<CBType> extend = new HashSet<>();
	private final Set<CBType> permits = new HashSet<>();
	private final Set<CBType> impl = new HashSet<>();
	private final Set<CBType> imports = new TreeSet<>();
	private final Set<Pair<CBType, String>> staticImports = new HashSet<>();
	public final Collection<Object> elements = new LinkedHashSet<>();

	public TextClassBuilder(String pack, String name, ClassType type) {
		this.pack = pack;
		this.name = name;
		this.type = type;
		annotation(new CBAnnotation(AutoGenerated.class));
	}

	private void validate() {
		if (type == ClassType.INTERFACE) {
			if (!impl.isEmpty()) {
				throw new IllegalStateException("implements on interface");
			}
			if (Modifier.isFinal(modifiers)) {
				throw new IllegalStateException("final interface");
			}
		} else if (extend.size() > 1) {
			throw new IllegalStateException("Multiple extends %s on type %s".formatted(extend, type));
		}
		if (Modifier.isFinal(modifiers)) {
			if (!permits.isEmpty()) {
				throw new IllegalStateException("final sealed");
			}
			if (Modifier.isAbstract(modifiers)) {
				throw new IllegalStateException("final abstract");
			}
		}
	}

	@Override
	public String toString() {
		validate();
		StringBuilder sb = new StringBuilder("package ").append(pack).append(";\n\n");

		if (!imports.isEmpty()) {
			for (CBType imp : imports) {
				if (imp.imports()) {
					sb.append("import ").append(imp.canonicalName()).append(";\n");
				}
			}
			sb.append("\n");
		}
		if (!staticImports.isEmpty()) {
			for (Pair<CBType, String> imp : staticImports) {
				sb.append("import static ").append(imp.a().canonicalName()).append(".").append(imp.b()).append(";\n");
			}
			sb.append("\n");
		}
		sb.append(bodyToString());
		return sb.toString();
	}


	public String bodyToString() {
		validate();
		StringBuilder sb = new StringBuilder();
		if (javadoc != null) {
			writeJavadoc(javadoc, sb, 0);
		}
		if (!annotations.isEmpty()) {
			for (CBAnnotation annotation : annotations) {
				sb.append(annotation).append("\n");
			}
		}
		appendModifiers(sb, modifiers);
		if (!permits.isEmpty()) sb.append("sealed ");
		sb.append(type.declaration).append(" ").append(name).append(" ");

		if (!extend.isEmpty()) {
			sb.append("extends ");
			for (CBType ex : extend) {
				sb.append(ex.name()).append(", ");
			}
			sb.setLength(sb.length() - 2);
			sb.append(" ");
		}
		if (!permits.isEmpty()) {
			sb.append("permits ");
			for (CBType ex : permits) {
				sb.append(ex.name()).append(", ");
			}
			sb.setLength(sb.length() - 2);
			sb.append(" ");
		}
		if (!impl.isEmpty()) {
			sb.append("implements ");
			for (CBType ex : impl) {
				sb.append(ex.name()).append(", ");
			}
			sb.setLength(sb.length() - 2);
			sb.append(" ");
		}

		sb.append("{\n\t");

		Class<?> lastElementType = null;

		for (Object e : elements) {
			if (lastElementType != e.getClass()) {
				lastElementType = e.getClass();
				sb.append("\n\t");
			}
			switch (e) {
				case String s -> writeComment(s, sb);
				case CBElement element -> element.write(sb);
				case CBJavadoc jd -> writeJavadoc(jd, sb);
				case TextClassBuilder tcb -> {
					if (tcb == this) throw new IllegalStateException("Recursion");
					writeTabbed(tcb.bodyToString(), sb);
				}
				default -> throw new IllegalArgumentException("Invalid class element " + e);
			}
			//sb.append("\n\t");
		}


		sb.setLength(sb.length() - 1);
		return sb.append("}").toString();
	}

	static void writeComment(Object comment, StringBuilder sb) {
		if (comment instanceof CBJavadoc javadoc) {
			writeJavadoc(javadoc, sb);
		} else if (comment instanceof String s) {
			writeComment(s, sb);
		} else throw new IllegalArgumentException("Illegal comment " + comment);
	}

	static void writeComment(String comment, StringBuilder sb) {
		if (comment.isEmpty()) return;
		String[] sa = comment.split("\n");
		if (sa.length == 1) {
			sb.append("// ").append(sa[0]);
		} else if (sa.length > 1) {
			sb.append("/*\n\t");
			for (int i = 0; i < sa.length; i++) {
				sb.append(sa[i]).append("\n\t");
			}
			sb.append("*/");
		}
		sb.append("\n\t");
	}

	static void writeTabbed(String value, StringBuilder sb) {
		String[] sa = value.split("\n");
		for (int i = 0; i < sa.length; i++) {
			sb.append(sa[i]).append("\n\t");
		}
	}

	static void writeJavadoc(CBJavadoc javadoc, StringBuilder sb) {
		writeJavadoc(javadoc, sb, 1);
	}

	static void writeJavadoc(CBJavadoc javadoc, StringBuilder sb, int tabs) {
		if (javadoc.lines().isEmpty()) return;
		sb.append("/**\n").repeat("\t", tabs)
				.append("*<pre>\n").repeat("\t", tabs);
		for (int i = 0; i < javadoc.lines().size(); i++) {
			sb.append("* ").append(javadoc.lines().get(i)).append("\n").repeat("\t", tabs);
		}
		sb.append("*</pre>").append("\n").repeat("\t", tabs)
				.append("**/\n").repeat("\t", tabs);
	}

	static void appendModifiers(StringBuilder sb, int modifiers) {
		if (Modifier.isPublic(modifiers)) {
			sb.append("public ");
		} else if (Modifier.isPrivate(modifiers)) {
			sb.append("private ");
		}
		if (Modifier.isStatic(modifiers)) {
			sb.append("static ");
		}
		if (Modifier.isFinal(modifiers)) {
			sb.append("final ");
		}
		if (Modifier.isSynchronized(modifiers)) {
			sb.append("synchronized ");
		}
		if (Modifier.isVolatile(modifiers)) {
			sb.append("volatile ");
		}
		if (Modifier.isTransient(modifiers)) {
			sb.append("transient ");
		}
		if (Modifier.isAbstract(modifiers)) {
			sb.append("abstract ");
		}
	}


	public TextClassBuilder setJavadoc(CBJavadoc javadoc) {
		this.javadoc = javadoc;
		return this;
	}

	public TextClassBuilder setFinal(boolean fnl) {
		this.modifiers = fnl ? (this.modifiers | Modifier.FINAL) : (this.modifiers & ~Modifier.FINAL);
		return this;
	}

	public TextClassBuilder setAbstract(boolean abs) {
		this.modifiers = abs ? (this.modifiers | Modifier.ABSTRACT) : (this.modifiers & ~Modifier.ABSTRACT);
		return this;
	}

	public TextClassBuilder setStatic(boolean stat) {
		this.modifiers = stat ? (this.modifiers | Modifier.STATIC) : (this.modifiers & ~Modifier.STATIC);
		return this;
	}

	public TextClassBuilder setPublic() {
		this.modifiers = (this.modifiers | Modifier.PUBLIC) & ~(Modifier.PRIVATE | Modifier.PROTECTED);
		return this;
	}

	public TextClassBuilder setPrivate() {
		this.modifiers = (this.modifiers | Modifier.PRIVATE) & ~(Modifier.PUBLIC | Modifier.PROTECTED);
		return this;
	}

	public TextClassBuilder setProtected() {
		this.modifiers = (this.modifiers | Modifier.PROTECTED) & ~(Modifier.PUBLIC | Modifier.PRIVATE);
		return this;
	}

	public TextClassBuilder setPackagePrivate() {
		this.modifiers &= ~(Modifier.PUBLIC | Modifier.PROTECTED | Modifier.PRIVATE);
		return this;
	}

	public TextClassBuilder comment(String comment) {
		elements.add(comment);
		return this;
	}

	public TextClassBuilder annotation(CBAnnotation annotation) {
		annotations.add(annotation);
		checkImport(annotation.type());
		return this;
	}

	public TextClassBuilder checkImport(CBType type) {
		if (this.pack.equals(type.pack())) {
			return this;
		}
		imports.add(type);
		return this;
	}

	public TextClassBuilder checkImport(Class<?> type) {
		return checkImport(CBType.of(type));
	}

	public TextClassBuilder importStatic(CBType clazz, String name) {
		staticImports.add(new Pair<>(clazz, name));
		return this;
	}

	public TextClassBuilder importStatic(Class<?> type, String name) {
		staticImports.add(new Pair<>(CBType.of(type), name));
		return this;
	}

	public TextClassBuilder permit(CBType type) {
		permits.add(type);
		checkImport(type);
		return this;
	}

	public TextClassBuilder permit(Class<?> type) {
		permits.add(CBType.of(type));
		checkImport(type);
		return this;
	}

	public TextClassBuilder implement(CBType type) {
		impl.add(type);
		checkImport(type);
		return this;
	}

	public TextClassBuilder implement(Class<?> type) {
		impl.add(CBType.of(type));
		checkImport(type);
		return this;
	}

	public TextClassBuilder extend(CBType type) {
		extend.add(type);
		checkImport(type);
		return this;
	}

	public TextClassBuilder extend(Class<?> type) {
		extend.add(CBType.of(type));
		checkImport(type);
		return this;
	}


	public TextClassBuilder addElement(Object e) {
		if (e instanceof CBElement element) {
			element.imports(this);
		} else if (e instanceof TextClassBuilder tcb) {
			for (CBType i : tcb.imports) checkImport(i);
		}
		elements.add(e);
		return this;
	}


}
